### PR TITLE
Make FileBrowseField return a FieldFile. Fix #69. Take 2.

### LINKED ISSUE #69: Make FileBrowseField return a FieldFile
[An issue](https://github.com/sehmaschine/django-filebrowser/issues/59) was opened for this a couple years ago in django-filebrowser, but it was closed without being understood.

See the docs on [FileField and FieldFile](https://docs.djangoproject.com/en/1.9/ref/models/fields/#filefield-and-fieldfile):

> When you access a FileField on a model, you are given an instance of FieldFile as a proxy for accessing the underlying file.

The motivation is primarily that reusable django apps tend to have functionality that depends on file fields returning a `FieldFile` instance. Examples that I'm aware of include [easy-thumnails](https://github.com/SmileyChris/easy-thumbnails) (as mentioned in the django-filebrowser issue) and [django-downloadview](https://github.com/benoitbryon/django-downloadview) (my use case).

I'm not yet sure if this is realistic -- it's not *just* a matter of changing the base class.

Potential Resolutions:

1. Make `FileBrowseField` [a subclass of `django.db.models.FileField`](https://docs.djangoproject.com/en/1.9/howto/custom-model-fields/#writing-a-filefield-subclass).
2. Have `FileBrowseField` return a `FieldFile` instance.
3. Make `FileObject` a subclass of `FieldFile`.
4. Have `FileBrowseField` implement the `FieldFile` API.

### PR DESCRIPTION
**Pull request by ryneeverett**
I believe all the issues that led to reversion of #70 have now been addressed.

### CODE REVIEW

**Comment by ryneeverett** [comment]
Btw, could you turn on travis?

**Comment by stephenmcd** [comment]
Travis is on now, I'll test the latest changes.

Thanks for all your help!

**Comment by stephenmcd** [comment]
Works great! Thanks again.

**Comment by ryneeverett** [comment]
Thank you for all the help on a feature nobody asked for!

**Pull request merged**
