### PR TITLE
Fix inline filefields (grappelli-safe #81).

### PR DESCRIPTION
**Pull request by ryneeverett**

### CODE REVIEW

**Comment by jerivas** [comment]
A small problem occurs when you remove the `href` attributes from the `<a>`. [The styling applied by Grappelli](https://github.com/stephenmcd/grappelli-safe/blob/master/grappelli_safe/static/grappelli/css/typography.css#L182-L188) breaks because `:link` doesn't match without `href` (tested in Firefox).

I tested adding `href="javascript:void(0);"` between lines 10 and 11 and that fixed it.

**Comment by ryneeverett** [comment]
Nice catch!

**Comment by nielsonsantana** [comment]
I tried and the bug was solved, but why no release was published pip?

**Comment by ryneeverett** [comment]
@nielsonsantana Like many projects, we don't release very frequently.

I don't recommend being dependent on *any* open source maintainer for releasing fixes and features you need for *your* project. I emphasize "your" because you own the results, not the developers of the tools you use. Pristine releases are a convenience you can't expect to always find, even in a large funded project like django.

I do recommend familiarizing yourself with and using [pip installation from git](https://pip.readthedocs.io/en/stable/reference/pip_install/#git) from either some commit on master or your own fork which you cherry-pick commits into. Often times (and right now as far as I know) it's fine to deploy from master, but I would generally recommend checking recent git history and avoiding this approach if there are recent major changes (particularly if they involve models/database).

**Comment by nielsonsantana** [comment]
@ryneeveret, I agree with you that the releases shouldn't be released too frequently.
However, I think that is a good pattern have a stable version of the project as release, just because is how the people use the project. I think that is a common thought.

But the real reason of my ask about the release is because I tried different versions(of the releases on pip) of mezzanine, grappelli-safe and filebrowser-safe, combining versions of the same period and anyone of them worked. I spend time on it and anyone of my tries worked. Others people maybe face the same problem. 
My dependence of new releases was because I updated the _django to 1.8 LTS_, once the previous versions (1.5, 1.6, 1.7) aren't supported anymore. It forced-me to update to mezzanine 4.x.x, but the project aren't working very well as before.
I solved the problems on **_my_** projects by forking the current version of **filebrowser-safe** and **grappelli-safe** and installing they from master using pip.
My ask wasn't only for me.

**Comment by ryneeverett** [comment]
> I think that is a good pattern have a stable version of the project as release, just because is how the people use the project. I think that is a common thought.

The thing is, every release we cut is going to have at least one bug that at least one person considers a show-stopper. At a certain point the solution is not for maintainers to do more release-cutting work but for users to do the work of finding a version that works for them. There have not been very many complaints about the current version and thus I consider it stable. There could be an even worse bug in our next release.

> But the real reason of my ask about the release is because I tried different versions(of the releases on pip) of mezzanine, grappelli-safe and filebrowser-safe, combining versions of the same period and anyone of them worked.

If you use the master versions of filebrowser-safe, grappelli-safe, and mezzanine and find bugs, please report them.

>  I solved the problem on my projects by forking the current version of filebrowser-safe and grappelli-safe and installing they from master using pip.
> My ask wasn't only for me.

I hope I didn't come across as hostile. Sometimes it takes a while for people to realize that they're empowered to solve their own problems and I probably chose an inappropriate place to vent on that topic.

**Pull request merged**
